### ISSUE TITLE
NPE when ingesting JSON trace file

### ISSUE THREAD

**Issue by JasonCromer** [sharedstreets/sharedstreets-matcher#13]
Using a standard GeoJson format to ingest, but it is currently failing when running `java -jar [path/to]/ingest-1.1.jar  --input myJsonFile.json --output json_gpx/ --type json`

My json input file looks like so:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.26795513194266,
          37.77275729927958
        ]
      },
      "properties": {
        "time": "2018-11-01T14:35:10.000Z",
        "timeUnix": 1541082910,
        "createdAt": "2018-11-01T14:35:52.409Z",
        "direction": 146.6015625,
        "speed": 1.659999966621399,
        "horizontalAccuracy": 30
      }
    },
...
...
...
}
```

The debug trace looks as follows:
```
02/11/2019 16:38:01	CHAIN DataSource (at main(Ingester.java:145) (org.apache.flink.api.java.io.TextInputFormat)) -> FlatMap (FlatMap at main(Ingester.java:148))(4/12) switched to FINISHED 
02/11/2019 16:38:01	DataSink (io.sharedstreets.matcher.ingest.Ingester$2@299a06ac)(1/1) switched to RUNNING 
02/11/2019 16:38:02	DataSink (io.sharedstreets.matcher.ingest.Ingester$2@299a06ac)(1/1) switched to FAILED 
java.lang.NullPointerException
	at io.sharedstreets.matcher.ingest.model.InputEvent.toProto(InputEvent.java:19)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:214)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:211)
	at org.apache.flink.runtime.operators.DataSinkTask.invoke(DataSinkTask.java:194)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)

02/11/2019 16:38:02	Job execution switched to status FAILING.
java.lang.NullPointerException
	at io.sharedstreets.matcher.ingest.model.InputEvent.toProto(InputEvent.java:19)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:214)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:211)
	at org.apache.flink.runtime.operators.DataSinkTask.invoke(DataSinkTask.java:194)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)
02/11/2019 16:38:02	Job execution switched to status FAILED.
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply$mcV$sp(JobManager.scala:897)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply(JobManager.scala:840)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$6.apply(JobManager.scala:840)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at io.sharedstreets.matcher.ingest.model.InputEvent.toProto(InputEvent.java:19)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:214)
	at io.sharedstreets.matcher.ingest.Ingester$2.writeRecord(Ingester.java:211)
	at org.apache.flink.runtime.operators.DataSinkTask.invoke(DataSinkTask.java:194)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JasonCromer** [comment]
@kpwebb

**Comment by JasonCromer** [comment]
Digging into the source code, it looks like since the JSON does not contain a `vehicle_id`, an NPE is thrown when creating a new `InputEvent`. Closing this.
